### PR TITLE
docs: update doc

### PR DESCRIPTION
**Pull request by Mini256**

### CODE REVIEW

**Comment by hi-rustin** [comment]
@Mini256  Better add a message to test it.

**Comment by Mini256** [comment]
> @Mini256 Better add a message to test it.

add a message ?

**Comment by hi-rustin** [comment]
> > @Mini256 Better add a message to test it.
> 
> add a message?

It seems you missed the reply function.

**Comment by hi-rustin** [comment]
We should support replying after adding or deleting to give an explanation of why the action was taken. Otherwise users will be confused to see the behavior of the bot.

**Comment by Mini256** [comment]
> We should support replying after adding or deleting to give an explanation of why the action was taken. Otherwise users will be confused to see the behavior of the bot.

Understand.

And now can we update the github client dependency to support issue events, maybe I want to solve both problems at the same time.

**Comment by hi-rustin** [comment]
> > We should support replying after adding or deleting to give an explanation of why the action was taken. Otherwise users will be confused to see the behavior of the bot.
> 
> Understand.
> 
> And now can we update the github client dependency to support issue events, maybe I want to solve both problems at the same time.

Cool

**Pull request merged**
