### PR TITLE
test: add 48 to README.md

### PR DESCRIPTION
**Pull request by Mini256**

### CODE REVIEW

**Comment by Mini256** [comment]
@hi-rustin :laughing: Could you please review this PR but don't merge it? I want to add the sig label after you finished the review, for the blunderbuss test.

**Review by hi-rustin — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]

**Comment by hi-rustin** [comment]
It's work now.

**Comment by hi-rustin** [comment]
@Mini256  I can use bot account help you test it.

**Comment by hi-rustin** [comment]
@Mini256 Try it now.

**Comment by Mini256** [comment]
Owners interface seems to be inaccessible

https://prow.tidb.io/ti-community-owners/repos/ti-community-infra/test-dev/pulls/248/owners

**Comment by hi-rustin** [comment]
> Owners interface seems to be inaccessible
> 
> https://prow.tidb.io/ti-community-owners/repos/ti-community-infra/test-dev/pulls/248/owners

https://prow-dev.tidb.io/ti-community-owners/repos/ti-community-infra/test-dev/pulls/248/owners

**Comment by Mini256** [comment]
OK, Thank you very much and sorry to disturb your rest.

**Pull request merged**
